#!/bin/bash

gcloud compute instances list --format='value(name,zone)' | \
while read -r line
do
    parts=($line)
    name=${parts[0]}
    zone=${parts[1]}
    gcloud compute ssh "$name" --zone="$zone" --command=exit --quiet
done
