steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/machine-stats-workshop', '.']
- name: 'gcr.io/cloudshell-images/custom-image-validation'
  args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/machine-stats-workshop']
images: ['gcr.io/$PROJECT_ID/machine-stats-workshop']
timeout: '1200s'